# AUTOGENERATED FILE -- RENAME OR YOUR EDITS WILL BE OVERWRITTEN
import unittest, exemplar
out_trace = ''  # Will receive each test's print()'ed values.
in_trace = []   # Assigned in each test to provide input() values to the function under test.


# print() is mocked to allow the tests a chance to recreate the .exem in out_trace.
def print(line: str = "") -> None:
    global out_trace
    out_trace += ">" + line + '\n'


# input() is mocked to simulate user entries and allow the tests to recreate the .exem in out_trace.
def input(line: str = "") -> str:
    global out_trace
    result = in_trace.pop(0)
    out_trace += "<" + result + '\n'  # Eg, '<Albert\n'
    return result


# The (working) sequential target function.
def guess4():
    print('Hello! What is your name?')
    name = input('name:')  # Eg, John
    secret = int(input('secret:'))  # Eg, 3
    print('Well, ' + str(name) + ', I am thinking of a number between 1 and 20.')
    guess_count=0
    assert guess_count==0
    print('Take a guess.')
    guess = int(input('guess:'))  # Eg, 11
    assert guess>secret  #if guess>secret:
    print('Your guess is too high.')
    guess_count = 1
    assert guess_count == 1
    print('Take a guess.')
    guess = int(input('guess:'))  # Eg, 1
    assert guess<secret  #if guess<secret:
    print('Your guess is too low.')
    guess_count=2
    assert guess_count==2
    print('Take a guess.')
    guess = int(input('guess:'))  # Eg, 2
    assert guess<secret  #if guess<secret:
    print('Your guess is too low.')
    guess_count=3
    assert guess_count==3
    print('Take a guess.')
    guess = int(input('guess:'))  # Eg, 10
    assert guess>secret  #if guess>secret:
    print('Your guess is too high.')
    guess_count=4
    assert guess_count==4
    print('Take a guess.')
    guess = int(input('guess:'))  # Eg, 9
    assert guess>secret  #if guess>secret:
    print('Your guess is too high.')
    guess_count=5
    assert guess_count==5
    print('Take a guess.')
    guess = int(input('guess:'))  # Eg, 8
    assert guess>secret  #if guess>secret:
    print('Your guess is too high.')
    print('Nope. The number I was thinking of was ' + str(secret) + '.')


# The (generated) function under test.
def guess4():
    print('Hello! What is your name?')
    name = input('name:')  # Eg, John
    secret = int(input('secret:'))  # Eg, 3
    print('Well, ' + str(name) + ', I am thinking of a number between 1 and 20.')
    for guess_count in range(0, 6):
        print('Take a guess.')
        guess = int(input('guess:'))  # Eg, 11
        if guess>secret:
            print('Your guess is too high.')
        elif guess<secret:
            print('Your guess is too low.')
        elif guess>secret:
            print('Nope. The number I was thinking of was ' + str(secret) + '.')


class TestGuess4(unittest.TestCase):

    def setUp(self):
        global out_trace
        out_trace = ''

    # Return the i/o statements of the named .exem file for comparison with out_trace.
    @staticmethod
    def get_expected(exem: str) -> str:
        out_exem_lines = []
        for line in exemplar.clean(exemplar.from_file(exem)):
            if line.startswith('<') or line.startswith('>'):
                out_exem_lines.append(line)
        return '\n'.join(out_exem_lines) + '\n'
    
    def test_guess41(self):
        global in_trace
        in_trace = ['John', '3', '11', '1', '2', '10', '9', '8']  # From an example of the .exem
        guess4()  # The function under test is used to write to out_trace.
        self.assertEqual(self.get_expected('guess4.exem'), out_trace)


if __name__ == '__main__':
    unittest.main()
