# AUTOGENERATED FILE -- RENAME OR YOUR EDITS WILL BE OVERWRITTEN
import unittest, exemplar
actual_io_trace = ''  # Receives test values print()'ed and input().
global_input = []   # Assigned in each test to provide input() values to the function under test.


# 3 functions unchanged from starter:
# print() is mocked to see if the tests recreate the .exem-specified i/o in actual_io_trace.
def print(line="") -> None:
    global actual_io_trace
    if line is str:
        line = line.translate(str.maketrans({"'": r"\'"}))  # Escape single quotes
    actual_io_trace += ">" + str(line) + '\n'


# input() is mocked to return the test-specified input as well as add it to actual_io_trace.
def input(variable_name: str = "") -> str:
    # (variable_name is ignored because it may not have been specified by the .exem.)
    global actual_io_trace
    result = global_input.pop(0)
    result = result.translate(str.maketrans({"'": r"\'"}))  # Escape single quotes
    actual_io_trace += "<" + result + '\n'  # Eg, '<Albert\n'
    return result


# The generated function under Stage 2 (i.e., a test per example) testing.
def sum_double():
    int1 = int(input("int1:"))  # Eg, 1
    int2 = int(input("int2:"))  # Eg, 2
    print(str(int1+int2))
    # return str(int1+int2) 
    if int1==int2:
        print('(4) * ' + str(int2))
        return '(4) * ' + str(int2) 


class TestSumDouble(unittest.TestCase):

    def setUp(self):
        global actual_io_trace
        actual_io_trace = ''
        self.maxDiff = None

    def test_sum_double7(self):
        global global_input
        global_input = ['1', '2']  # From the .exem
        sum_double()  # The function under test is used to write to actual_io_trace.
        self.assertEqual('''<1
<2
>3
''', actual_io_trace)

    def test_sum_double14(self):
        global global_input
        global_input = ['3', '2']  # From the .exem
        sum_double()  # The function under test is used to write to actual_io_trace.
        self.assertEqual('''<3
<2
>5
''', actual_io_trace)

    def test_sum_double22(self):
        global global_input
        global_input = ['2', '2']  # From the .exem
        sum_double()  # The function under test is used to write to actual_io_trace.
        self.assertEqual('''<2
<2
>4
>(4) * 2
''', actual_io_trace)


if __name__ == '__main__':
    unittest.main()
